config/routes.rb
Trellino::Application.routes.draw do
  resources :boards, only: [:index, :show, :create, :update, :destroy] do
    resources :lists, only: [:index, :show, :create, :update, :destroy]
  end
  resources :lists, only: [] do
    resources :cards, only: [:index]
  end
  resources :cards, only: [:create, :update, :destroy, :show] do
    resources :todo_items, only: [:create, :update, :destroy]
  end
  resources :card_assignments, only: :destroy
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]
  root to: 'static#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trellino</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="navbar-inner">
      <ul class="nav">
        <li>
          <span class="title">Trellino</span>
        </li>
      </ul>
      <% if current_user %>
        <div class="nav navbar-text navbar-right">
          Logged in as <%= current_user.email %>
        </div>
        <%= button_to "Log Out", session_url, method: :delete, class: "nav navbar-btn btn btn-primary navbar-right" %>
        </form>
      <% else %>
        <div class="nav navbar-btn btn btn-primary navbar-right">
          <%= link_to "Sign In", new_session_url %>
        </div>
      <% end %>
    </div>
  </nav>
  <%= yield %>

<div id="content" class="container">
</div>

<div class="overlay hidden">
</div>

</body>
</html>